spring:
  application:
    name: smarttax

  datasource:
    url: jdbc:mysql://localhost:3306/smarttax
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver


  #update	필요한 부분만 수정	✅ 유지
  #create	전부 지우고 새로 생성	❌ 삭제
  #create-drop	실행 시 생성, 종료 시 삭제	❌ 종료하면 삭제
  #validate	맞는지만 검사	✅ 유지
  #none	아무것도 안 함	✅ 유지
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true